### ISSUE TITLE
Bringing up a cluster with fabric8 enabled and then deleting cr.yaml puts the cluster in a state where OC health check fails

### ISSUE THREAD

**Issue by brian-avery** [Maistra/origin#1]
##### Version
istiooc/OCP 3.10

##### Steps To Reproduce
1. Create an OC cluster (community or OCP)
2. use the attached yaml to initialize the operator
3. wait for everything to initialize
4. delete the yaml
 oc delete -n istio-operator -f cr.yml
5. observe that after a couple of minutes, the cluster is no longer accessible

##### Current Result
Cluster enters an unhealthy state

##### Expected Result
Cluster gets cleaned up properly

##### Additional Information
Diagnostics
oc adm diagnostics
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at '/home/bavery/go/src/istio.io/istio/.circleci/config'

ERROR: [CED1008 from controller openshift/origin/pkg/oc/admin/diagnostics/cluster.go]
       Unknown error testing cluster-admin access for context 'myproject/127-0-0-1:8443/system:admin':
       Post https://127.0.0.1:8443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews: dial tcp 127.0.0.1:8443: getsockopt: connection refused
       
ERROR: [CED1008 from controller openshift/origin/pkg/oc/admin/diagnostics/cluster.go]
       Unknown error testing cluster-admin access for context 'default/127-0-0-1:8443/system:admin':
       Post https://127.0.0.1:8443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews: dial tcp 127.0.0.1:8443: getsockopt: connection refused
       
[Note] Could not configure a client with cluster-admin permissions for the current server, so cluster diagnostics will be skipped

[Note] Running diagnostic: ConfigContexts[default/127-0-0-1:8443/system:admin]
       Description: Validate client config context is complete and has connectivity
       
ERROR: [DCli0015 from diagnostic ConfigContexts@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/client/config_contexts.go:299]
       For client config context 'default/127-0-0-1:8443/system:admin':
       The server URL is 'https://127.0.0.1:8443'
       The user authentication is 'system:admin/127-0-0-1:8443'
       The current project is 'default'
       (*url.Error) Get https://127.0.0.1:8443/apis/project.openshift.io/v1/projects: dial tcp 127.0.0.1:8443: getsockopt: connection refused
       Diagnostics does not have an explanation for what this means. Please report this error so one can be added.
       
[Note] Running diagnostic: ConfigContexts[myproject/127-0-0-1:8443/developer]
       Description: Validate client config context is complete and has connectivity
       
ERROR: [DCli0015 from diagnostic ConfigContexts@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/client/config_contexts.go:299]
       For client config context 'myproject/127-0-0-1:8443/developer':
       The server URL is 'https://127.0.0.1:8443'
       The user authentication is 'developer/127-0-0-1:8443'
       The current project is 'myproject'
       (*url.Error) Get https://127.0.0.1:8443/apis/project.openshift.io/v1/projects: dial tcp 127.0.0.1:8443: getsockopt: connection refused
       Diagnostics does not have an explanation for what this means. Please report this error so one can be added.
       
[Note] Running diagnostic: DiagnosticPod
       Description: Create a pod to run diagnostics from the application standpoint
       
ERROR: [DCli2001 from diagnostic DiagnosticPod@openshift/origin/pkg/oc/admin/diagnostics/diagnostics/client/pod/run_diagnostics_pod.go:97]
       Creating diagnostic pod with image registry.access.redhat.com/openshift3/ose-deployer:v3.10.14 failed. Error: (*url.Error) Post https://127.0.0.1:8443/api/v1/namespaces/myproject/pods: dial tcp 127.0.0.1:8443: getsockopt: connection refused
       
[Note] Summary of diagnostics execution (version v3.10.14):
[Note] Errors seen: 5

#####  OC cluster status 
istiooc cluster status
Error: OpenShift cluster health check failed

[cr.yaml.txt](https://github.com/Maistra/origin/files/2325699/cr.yaml.txt)

**Comment by knrc** [comment]
@brian-avery If you are still seeing this can you report it in the Maistra jira?  Thanks very much
